### PR TITLE
GitHub worklfow greeting

### LINKED ISSUE #5: Github Action Workflow
### Is your feature request related to a problem? Please describe
We want to greet every pull request and issue raised in the repository 
### Describe the solution you'd like
You can create a workflow for that 
```yaml
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
```

### PR DESCRIPTION
**Pull request by abhishak3**
## Description

_Added Github Workflow for greeting users through comments on opening issues and pull requests_ <br />

Fixes #5 

### On Issues
image
### On Pull Requests
image

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by Abbhiishek** [comment]
Looks Good to me @abhishak3 

Can you customise the greeting message a bit with little bit  of introduction about the repository.

**Comment by abhishak3** [comment]
"Welcome to Webners! This repository is all about contributing your new Web Projects or improving the current ones, Documentation or any resources which can help developers upskill themselves.
Thank you for showing interest in this repository. We'll get back to you soon!"
Is this greeting message OK?

**Comment by Abbhiishek** [comment]
>  LGTM ✨

**Comment by Abbhiishek** [comment]
Thanks @abhishak3  for your valuable Contribution ☺️

**Comment by abhishak3** [comment]
Should I update now ?

**Comment by Abbhiishek** [comment]
yep you can 
make sure you repull the files as there might be some changes

**Comment by Abbhiishek** [comment]
Am removing `hacktoberfest-accepted` label for now 
Let me know after you commit the changes , then will assign the label again :)
Also If you found this repository helpful , do Give us a Star ⭐

**Pull request merged**
