### PR TITLE
Added contributors-website

### LINKED ISSUE #4: A Website to list all the contributors
### Is your feature request related to a problem? Please describe
We need a dynamic website that list all the contributors and their contribution to this repository.

### Describe the solution you'd like
We suggest to get the data from `CONTRIBUTORS.json` file and render the website.

### PR DESCRIPTION
**Pull request by Amarjit-Khan**
## Description

#4 A website to list down names and description of all contributors of this repo from a json file.
This commit fixes #4 

## Dependencies

npm package

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@Abbhiishek 

## Screenshots of relevant screens
Screenshot (74)

### CODE REVIEW

**Comment by Abbhiishek** [comment]
Hey @Amarjit-Khan 
Thanks for your contribution.
Can you also add the project file in root directory as we might deploy through vercel or netlify.
Also your sub modules are not visible to me .

**Comment by Abbhiishek** [comment]
Looks like we have some merge Conflicts, Let me know if you can fix it 

Hint : Repull the main branch for updated file ☺️

**Comment by Amarjit-Khan** [comment]
Can I close this PR and go for a new one? I was able to solve the conflict but the submodule link is not being shown. I will pull the repo clean and make the changes properly.

**Comment by Abbhiishek** [comment]
Okay go for it

**Pull request closed without merging**
