### PR TITLE
Added contribution-website

### LINKED ISSUE #4: A Website to list all the contributors
### Is your feature request related to a problem? Please describe
We need a dynamic website that list all the contributors and their contribution to this repository.

### Describe the solution you'd like
We suggest to get the data from `CONTRIBUTORS.json` file and render the website.

### PR DESCRIPTION
**Pull request by Amarjit-Khan**
## Description

Created a website to list names and contributions of all contributors

Fixes #4 

## Dependencies

npm package

## Future Improvements

None

## Mentions

@Abbhiishek 

## Screenshots of relevant screens
Screenshot (74)

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by Abbhiishek** [comment]
Hey @Amarjit-Khan  you are not committing the files rather linking with your own repository.

These script would be used for documentation and also have to be in root of the repository so that we can deploy that.

Make the necessary changes and let me know.
Then we can merge the PR.

**Comment by Amarjit-Khan** [comment]
Can you suggest a way or documentation for the same as I am not able to upload the react folders in the contributions folder. The react folder is already a git repo and on keeping it inside contributions(another repo or part of one), it gets created as a submodule. I tried removing all folders and just uploading the build folder but its all the same.

**Comment by Abbhiishek** [comment]
do one thing make changes to root directory 
image

here and create a react app over here only not in Contribution folder.
I hope this way the conflict might be removed 🤩

**Comment by Amarjit-Khan** [comment]
I removed all folders and kept the build folder only. The build folder has everything to host a static website. But the vercel deployment failed so ig I have to do it that way only.

**Comment by Abbhiishek** [comment]
keep both the way so that your changes are also there in Contribution Folder and root

**Comment by Abbhiishek** [comment]
Also a small suggestion for Avatar 
We have GitHub profile link in json file
Add .png at last gives us the avatar of that person . This way we can add Contributors pic in site.

Example :

http://github.com/Abbhiishek    ->  Gives you full profile

http://github.com/Abbhiishek.png -> redirect you to Avatar pic


This may help ☺️

**Comment by Abbhiishek** [comment]
Make Sure you give us a Star

**Comment by Amarjit-Khan** [comment]
I finally gave up with the react 🥲  and created the same using html, css and js. So will I make a folder under Contributions and keep the files like the rest contributors or keep it in the root directory like this: 
Screenshot 2022-10-03 161315

And the resultant ss with the avatar

Screenshot 2022-10-03 161353

**Comment by Abbhiishek** [comment]
Keep under contribution folder  👍

**Comment by Amarjit-Khan** [comment]
Done successfully. There are  few unwanted commits. Please remove them if needed 😃 .

**Comment by Abbhiishek** [comment]
Great Work 🤩

**Pull request merged**
